name: Oscar FR Log
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19896
title: Oscar FR Log
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b7c6d9'
    - '#091a2e'
    - '#536887'
    - '#77fdfd'
  brandStrength: 0.25
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
