layout_spectrum: 0.5260143831837922
typography_spectrum: 0.6971164438873529
color:
  brandColors:
    - '#00FEBE'
    - '#DDDBF1'
    - '#42CAFC'
    - '#0E7C7B'
    - '#393E41'
  brandStrength: 0.0042593691032379866
  lightness: 0.949145887279883
  saturation: 0.03964620712213218
  rhythmicContrast: 0.012420143000781536
opengraph:
  image: null
  type: website
  appId: null
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
author:
  name: Oscar F
  email: oscar@vfx.rocks
  url: vfx.rocks
name: Oscar Log
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7704b5ba-30fa-4f19-9f04-1f9eb2dfa2a2.ico
title: Log
description: Oscar F
purpose: []
