typography_spectrum: 0.19896
color:
  brandColors:
    - '#ffffff'
    - '#b7c6d9'
    - '#091a2e'
    - '#536887'
    - '#77fdfd'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
author:
  name: Oscar F
  email: oscar@vfx.rocks
  url: vfx.rocks
name: Oscar Log
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Log
description: Oscar F
purpose: []
