typography_spectrum: 0.19896
color:
  brandColors:
    - '#ffffff'
    - '#b7c6d9'
    - '#091a2e'
    - '#536887'
    - '#77fdfd'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: website
  appId: null
layout_spectrum: 1
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
author:
  name: Oscar F
  email: oscar@vfx.rocks
  url: vfx.rocks
name: Oscar Log
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7704b5ba-30fa-4f19-9f04-1f9eb2dfa2a2.ico
title: Log
description: Oscar F
purpose: []
