layout_spectrum: 0.32789515028707683
typography_spectrum: 0.9656257014721632
color:
  brandColors:
    - '#C90F74'
    - '#32F9C0'
    - '#FFF9FF'
    - '#E6B3D4'
    - '#AE7891'
  brandStrength: 0.07693837024271488
  lightness: 0.1355900806374848
  saturation: 0.7016535422299057
  rhythmicContrast: 0.6948023582808673
opengraph:
  image: null
  type: website
  appId: null
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
author:
  name: Oscar F
  email: oscar@vfx.rocks
  url: vfx.rocks
name: Oscar Log
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7704b5ba-30fa-4f19-9f04-1f9eb2dfa2a2.ico
title: Log
description: Oscar F
purpose: []
