layout_spectrum: 0.5260143831837922
typography_spectrum: 0.9905720097012818
color:
  brandColors:
    - '#00FEBE'
    - '#DDDBF1'
    - '#42CAFC'
    - '#0E7C7B'
    - '#393E41'
  brandStrength: 0.1230465630069375
  lightness: 0.5325649238657206
  saturation: 0.13132628425955772
  rhythmicContrast: 0.7945256344974041
opengraph:
  image: null
  type: website
  appId: null
analytics:
  google: UA-42516166-4
  facebook: null
  twitter: null
author:
  name: Oscar F
  email: oscar@vfx.rocks
  url: vfx.rocks
name: Oscar Log
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/7704b5ba-30fa-4f19-9f04-1f9eb2dfa2a2.ico
title: Log
description: Oscar F
purpose: []
